// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:qola_app/core/base/reflection.dart' as prefix0;
import 'package:qola_app/modules/order/domain/entities/employee_entity.dart'
    as prefix1;
import 'package:qola_app/modules/order/domain/entities/table_entity.dart'
    as prefix2;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'EmployeeEntity',
            r'.EmployeeEntity',
            134217735,
            0,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => ({id, uid, fullName, charge, restaurantId}) => b
                  ? prefix1.EmployeeEntity(
                      charge: charge,
                      fullName: fullName,
                      id: id,
                      restaurantId: restaurantId,
                      uid: uid)
                  : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix1.EmployeeEntity.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'save': 0,
              r'delete': 0,
              r'box': 0,
              r'key': 0,
              r'isInBox': 0,
              r'toJson': 0,
              r'id': 0,
              r'id=': 1,
              r'uid': 0,
              r'uid=': 1,
              r'fullName': 0,
              r'fullName=': 1,
              r'charge': 0,
              r'charge=': 1,
              r'restaurantId': 0,
              r'restaurantId=': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'TableEntity',
            r'.TableEntity',
            134217735,
            1,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => ({id, name, isOccupied, restaurantId}) => b
                  ? prefix2.TableEntity(
                      id: id,
                      isOccupied: isOccupied,
                      name: name,
                      restaurantId: restaurantId)
                  : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix2.TableEntity.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'save': 0,
              r'delete': 0,
              r'box': 0,
              r'key': 0,
              r'isInBox': 0,
              r'toJson': 0,
              r'id': 0,
              r'id=': 1,
              r'name': 0,
              r'name=': 1,
              r'isOccupied': 0,
              r'isOccupied=': 1,
              r'restaurantId': 0,
              r'restaurantId=': 1
            })
      ],
      null,
      null,
      <Type>[prefix1.EmployeeEntity, prefix2.TableEntity],
      2,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'save': (dynamic instance) => instance.save,
        r'delete': (dynamic instance) => instance.delete,
        r'box': (dynamic instance) => instance.box,
        r'key': (dynamic instance) => instance.key,
        r'isInBox': (dynamic instance) => instance.isInBox,
        r'toJson': (dynamic instance) => instance.toJson,
        r'id': (dynamic instance) => instance.id,
        r'uid': (dynamic instance) => instance.uid,
        r'fullName': (dynamic instance) => instance.fullName,
        r'charge': (dynamic instance) => instance.charge,
        r'restaurantId': (dynamic instance) => instance.restaurantId,
        r'name': (dynamic instance) => instance.name,
        r'isOccupied': (dynamic instance) => instance.isOccupied
      },
      {
        r'id=': (dynamic instance, value) => instance.id = value,
        r'uid=': (dynamic instance, value) => instance.uid = value,
        r'fullName=': (dynamic instance, value) => instance.fullName = value,
        r'charge=': (dynamic instance, value) => instance.charge = value,
        r'restaurantId=': (dynamic instance, value) =>
            instance.restaurantId = value,
        r'name=': (dynamic instance, value) => instance.name = value,
        r'isOccupied=': (dynamic instance, value) => instance.isOccupied = value
      },
      null,
      [
        const [0, 0, null],
        const [1, 0, null],
        const [
          0,
          0,
          const [#id, #uid, #fullName, #charge, #restaurantId]
        ],
        const [
          0,
          0,
          const [#id, #name, #isOccupied, #restaurantId]
        ]
      ])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
