name: qola_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  get_it: ^7.2.0
  intl: ^0.17.0
  reflectable: ^3.0.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  formz: ^0.4.1
  dartz: ^0.10.1
  flutter_svg: ^1.1.5
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  mime: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/icons/
  fonts:
    - family: Forum
      fonts:
        - asset: assets/fonts/Forum-Regular.ttf
